name: whatsapp_direct_send
description: "A Flutter plugin to send text messages and/or images directly to a WhatsApp contact on Android via ACTION_SEND intents."
version: 0.2.1

repository: https://github.com/macss-dev/whatsapp_direct_send
homepage: https://github.com/macss-dev/whatsapp_direct_send
issue_tracker: https://github.com/macss-dev/whatsapp_direct_send/issues
documentation: https://pub.dev/documentation/whatsapp_direct_send/latest

environment:
  sdk: ^3.10.8
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.macss.whatsapp_direct_send
        pluginClass: WhatsappDirectSendPlugin

topics:
  - whatsapp
  - sharing
  - macss
